name: test

on:
  workflow_dispatch:

  pull_request:
    branches: [ master ]
    
env:
  BRANCH_NAME: ${{ github.event.pull_request.head.ref }}

jobs:
  branch-check:
    runs-on: ubuntu-latest
    outputs:
      pass: ${{ steps.branch-name-check.outputs.pass }}
    steps:
      - name: branch name check
        id: branch-name-check
        if: ${{ !startsWith(env.BRANCH_NAME, 'feature/') && !startsWith(env.BRANCH_NAME, 'hotfix/') && env.BRANCH_NAME != 'main' && env.BRANCH_NAME != 'cbt' && env.BRANCH_NAME != 'release' }}
        run : echo "::set-output name=pass::true"
      - run: echo ${{ pass }}
        
  pre-requirements-check:
    needs: branch-check
    if: ${{ needs.branch-check.outputs.pass == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: echo1
        run: echo ${{ env.BRANCH_NAME }}
        
      - name: echo2
        run: echo ${{ startsWith( env.BRANCH_NAME, 'release') }}
        
      - name: branch name check before
        if: ${{ env.BRANCH_NAME != 'release' }}
        run : echo "not same"
        
      - name: finish
        run : echo "finish"
